### ISSUE TITLE
JWT 활용에 따른 Entity Proxy 범위 처리

### ISSUE THREAD

**Issue by dujong** [Simbongsaa/Back#1]
### 문제 상황
- Spring Security + JWT을 활용한 인증 로직에서는 해당 토큰에서 유효한 값(유저 정보 등)을 꺼내서 Spring Security의 SecurityContextHolder에 저장한 뒤, Controller layer에서 @AuthenticationPrincipal 어노테이션 기능을 활용하여 저장되어 있는 값을 꺼내서 사용한다.
- 이 시점에서 SecurityContextHolder에 어떤 값을 저장할지가 고민인데 선택지는 아래와 같다.
  A. Member Entity를 등록
  B. Member Entity의 id만 등록

### A 로직
- Member Entity가 등록되어 있어 DB에서 따로 findById() 로직을 실행하지 않아도 되지만, Fetch.LAZY 전략을 사용하기 위해서는 OSIV를 활용하여 범위를 늘려줘야 하기 때문에, 추후에 많은 리소스 낭비 혹은 장애로 이어질 수 있다. 😢 
### B 로직
- Member Entity의 id가 등록되어 있어 Service layer에서 findById()로 Member를 불러와서 사용해야 한다. DB에 접근하는 시간이 있지만 @Transaction이 있는 Service layer에서 불러온 것이기 때문에 Fetch.LAZY 전략을 활용할 수 있다. 🚶 

### 결론
- B 로직을 활용하는 것이 맞다고 생각 💯

**Comment by lsh2613** [comment]
너무 명료하게 정리해주셔서 바로 납득이 가네요. 제가 봐도 B로직으로 가는 것이 맞다고 생각합니다!
