### ISSUE TITLE
팔로우, 팔로우 요청, 언팔, 팔로우 요청 삭제 기능에 대한 구현 방법

### ISSUE THREAD

**Issue by lsh2613** [Simbongsaa/Back#16]
### 이전 이슈에 대한 언급
![image](https://github.com/user-attachments/assets/d26a13d0-3d5a-40fb-83c3-2353d32e4fa9)

![image](https://github.com/user-attachments/assets/fc0e3178-99e5-4d0b-821e-efbca92256b8)

**Comment by lsh2613** [comment]
### 1. follows() 메소드를 follow service로 옮기는게 맞는가?
- 먼저 이 내용을 되게 많이 고민했었는데 "팔로우 요청은 follow service에 있는데 팔로우 요청 리스트 반환은 follow requests service에 있는게 왜?라는 의문" 이 내용이 저는 Follows에 대해서도 똑같이 적용되었습니다. **팔로우 요청은 follows-requests service에 있는데 팔로우 리스트 반환은 follow service에 있다는 의문**이 들었습니다
- 마땅한 묘수가 생각나지 않아서 Follows, FollowsRequest 어느 도메인 하나를 택해야 한다고 생각했었습니다. 그래도 팔로우 관련이므로 주축이 되는 건 Follows라고 생각해서 옮길까   ##했었습니다

### 2. 지금은 아래와 같은 구조같아요
follows requests
ㄴ 팔로우 요청
ㄴ PRIVATE or PUBLIC
ㄴ 팔로우 삭제
ㄴ PRIVATE or PUBLIC

정확히는 
ㄴ 팔로우 요청
    ㄴ PRIVATE or PUBLIC
ㄴ 팔로우 요청 삭제
    ㄴ 상태값에 무관하게 바로 처리

팔로우 삭제는 이후 개발하게 될 Follows에서 추가로 구현할 생각이었습니다

### 🥇 제안해주신 구조
"하나의 service가 하나의 repository를 의존하고 있어서 유지보수가 용이하고 객제지향적"는 저도 동의합니다
다만 정확히 이해가 가지 않는 부분은 private -> Follows Requests db 접근, public -> follows db만 접근하도록 하라는 것은 팔로우 요청에 대해서 말씀하시는 걸까요? 팔로우 삭제, 팔로우 요청 삭제는 각각 도메인에 맞는 Service 계층에서 처리가 가능합니다!
위 전제가 맞다면 팔로우에 대해서 어떻게 처리해야 해당 db만 접근하게 만들 수 있을까요?

아래 코드와 같이 아예 다음과 같이 요청url을 구분하고 해당하는 memberStatus가 아니라면 에러를 발생하도록 하는 로직을 생각하신 건가요?
``` java
    // Follows Controller
    public CustomApiResponse followsByPublic(...,
                                             @RequestParam MemberStatus memberStatus){
        ...
    }

    // FollowsRequests Controller 
    public CustomApiResponse followsByPrivate(...,
                                             @RequestParam MemberStatus memberStatus){
        ...
    }
```

**Comment by dujong** [comment]
네네 맞아요 A 사용자가 B사용자의 프로필에 방문에서 팔로우 요청을 한다는 가정하에 설명을 드리겠습니다.
1. Client에서 A사용자가 B사용자의 프로필에 방문
2. Server는 B사용자의 정보(memberStatus를 포함)를 반환
3. 팔로우 버튼을 누를 때, Server에서 받아온 사용자의 정보가 Private이라면 FollowsRequests Controller URL로 요청, Public이라면 Follows Controller URL로 요청을 하면 되겠죠!?

**Comment by lsh2613** [comment]
어떻게든 한 쪽에서 처리하려고 하다 보니 그런 방법을 생각 못하고 있었네요. 저도 종두님 의견이 좋을 것 같아요
우선 기능은 다 만들어 놨으니 추후에 해당 내용으로 리팩토링 진행해보겠습니다!

**Comment by dujong** [comment]
네네 혹시 중간에 더 좋은 방법 발견하시면 공유해주셔요!
