### ISSUE TITLE
Group leader 관리에 대한 이슈

### ISSUE THREAD

**Issue by lsh2613** [Simbongsaa/Back#6]
### 문제상황 
Group 테이블에서 group_leader로 그룹장을 관리하는데 Group-User 테이블에서도 role을 통해 leader, volunteer를 구분한다.
<img width="237" alt="image" src="https://github.com/Simbongsaa/Back/assets/104637774/f0f477bb-a954-44c1-bca4-89dc80c31276">
<img width="348" alt="image" src="https://github.com/Simbongsaa/Back/assets/104637774/4d1571d6-f6fe-4760-b47c-5b0f493a2212">

### 의견
해당 테이블들을 사용할 때는 대표적으로 그룹에 대한 상세 페이지를 제공할 때 팀원들을 띄워줄 때라고 생각한다.
이때 그룹 정보와 그룹 팀원 정보를 해주기 위해 Group과 Group-User 테이블을 조인해서 사용할 거기 때문에 두 테이블에서 모두 leader를 관리해줄 필요가 없다고 생각.

따라서 leader는 Group 혹은 Group-User 하나의 테이블에서만 관리해주면 되는데 Group-user에서 모든 팀원들에 대해 role을 관리하는 것보단 Group에서 leader의 유저id만 저장해서 관리하고 Group-User의 role을 없애는 건 어떨까요?

**Comment by dujong** [comment]
"Group에서 leader의 유저id만 저장해서 관리하고 Group-User의 role을 없애는 건 어떨까요?"

위 처럼 생각하신 이유가 궁금합니다~!

**Comment by lsh2613** [comment]
단순히 Group-role을 관리한다고 치면 팀원이 6명일 때 6개의 상태를 관리해야 하지만  Group-leaer_id에서는 하나만 관리하면 되고 저장용량적인 측면에서도 더 효율적이라고 생각했습니다

**Comment by dujong** [comment]
네네 이해했습니다 :)
